method: 2 # 方案一；修复策略，方案二：模板策略
templateset: 1 # 采用模板策略时，采用哪个模板, 可以是字符串，或者数字
fileName:
  - ssrsub-vless.txt
  - ssrsub-hysteria2.txt
fileYaml:
  - default.yaml
strategy-anchor:
  # 锚点
  # 负载均衡策略
  # round-robin 将会把所有的请求分配给策略组内不同的代理节点
  # consistent-hashing 将相同的 目标地址 的请求分配给策略组内的同一个代理节点
  # sticky-sessions: 将相同的 来源地址 和 目标地址 的请求分配给策略组内的同一个代理节点，缓存 10 分钟过期
  # BaseCR: &BaseCR { type: load-balance, interval: 300, lazy: true, hidden: true, include-all: true, strategy: round-robin }
  # BaseCH: &BaseCH { type: load-balance, interval: 300, lazy: true, hidden: true, include-all: true, strategy: consistent-hashing }
  BaseCR: &BaseCR
    type: load-balance
    interval: 300
    lazy: true
    strategy: round-robin

  BaseCH: &BaseCH
    type: load-balance
    interval: 300
    lazy: true
    strategy: consistent-hashing

groups-strategy:
  providers: { <<: *BaseCH }
providers:
  - name: vvTec
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/free18/v2ray/main/c.yaml
    main: true
  - name: newpac
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/YouAreHuman/updatePac/master/newpac.yaml
  - name: xrayvip
    type: base64
    url:
      - https://www.xrayvip.com/free.txt
  - name: freeV2net
    type: base64
    url:
      - https://xmxosfepggzm.503403.xyz
  - name: ssrsub
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/ssrsub/ssr/master/clash.yaml
  - name: ermao
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - name: fanpx
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
      - https://gh-proxy.com/raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml
  - name: anaer
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/anaer/Sub/main/proxies.yaml
  - name: peasoft
    type: yaml
    url:
      - https://gh-proxy.com/raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.meta.yml

templates:
  - name: wanswu
    url: >-
      https://gh-proxy.com/raw.githubusercontent.com/HenryChiao/MIHOMO_YAMLS/main/THEYAMLS/General_Config/wanswu/config.yaml
    providersAnchorUrl: ProvidersURL
    providersAnchorFile: ProvidersFILE
    providersDir: proxy_providers
    override:
      upd: true
      additional-prefix: '|'
    dns: false
    rules: false
    tun:
      enable: true

fix:
  base:
    # 通用配置
    mode: rule
    ipv6: true
    mixed-port: 7890
    allow-lan: true
    bind-address: '*'
    log-level: warning
    unified-delay: true
    find-process-mode: strict
    tcp-concurrent: true
    keep-alive-interval: 15
    keep-alive-idle: 600
    # 规则选择缓存
    profile:
      store-selected: true
      store-fake-ip: true
    # DNS配置
    dns:
      enable: true
      ipv6: true
      prefer-h3: false
      use-hosts: true
      listen: 0.0.0.0:1053
      use-system-hosts: true
      respect-rules: true
      enhanced-mode: fake-ip
      fake-ip-range: 198.18.0.1/16
      fake-ip-range6: fdfe:dcba:9876::/64
      fake-ip-filter:
        - RULE-SET:Lan
        - RULE-SET:China
      fallback:
        - https://dns.cloudflare.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
        - https://dns.google/dns-query#ecs=8.8.8.8/24&ecs-override=true
      default-nameserver: # 默认 DNS, 用于解析 DNS 服务器 的域名，必须为 IP, 可为加密 DNS
        - tls://223.5.5.5
        - tls://119.29.29.29
        - tls://8.8.8.8
      nameserver: # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
        - https://dns.cloudflare.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
        - https://dns.google/dns-query#ecs=8.8.8.8/24&ecs-override=true
      proxy-server-nameserver: # 代理节点域名解析服务器，仅用于解析代理节点的域名
        - https://doh.pub/dns-query#ecs=223.5.5.5/24&ecs-override=true
        - https://dns.alidns.com/dns-query#ecs=223.5.5.5/24&ecs-override=true
      direct-nameserver:
        - https://doh.pub/dns-query#ecs=223.5.5.5/24&ecs-override=true
        - https://dns.alidns.com/dns-query#ecs=223.5.5.5/24&ecs-override=true
      direct-nameserver-follow-policy: true
      nameserver-policy: # 指定域名查询的解析服务器，优先于 nameserver/fallback 查询
        'RULE-SET:China,Lan':
          - https://doh.pub/dns-query#ecs=223.5.5.5/24&ecs-override=true
          - https://dns.alidns.com/dns-query#ecs=223.5.5.5/24&ecs-override=true

    # GEO配置
    geodata-mode: false
    geo-auto-update: true
    geo-update-interval: 24
    geodata-loader: memconservative
    geox-url:
      geoip: >-
        "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
      mmdb: >-
        "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
      geosite: >-
        "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
      asn: >-
        "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

    # 入站
    tun:
      enable: true
      stack: mixed
      auto-route: true
      auto-redirect: true
      auto-detect-interface: true
      dns-hijack: [any:53, tcp://any:53]

    # 嗅探
    sniffer:
      enable: true
      parse-pure-ip: true
      override-destination: true
      sniff:
        TLS:
          ports: [443, 8443]
        HTTP:
          ports: [80, 8080-8880]
          override-destination: true
        QUIC:
          ports: [443, 8443]
      skip-domain:
        - Mijia Cloud
        - '+.push.apple.com'

    # 实验性功能
    experimental:
      quic-go-disable-gso: true

    # 面板设置
    external-ui-name: zashboard
    external-ui: ui
    external-ui-url: >-
      https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
    # secret: "Wans"
    external-controller: '127.0.0.1:9090'
  rules: []
  rule-anchor:
    # 规则集锚点
    BehaviorDN:
      &BehaviorDN { type: http, interval: 86400, format: mrs, behavior: domain }
    BehaviorIP:
      &BehaviorIP { type: http, interval: 86400, format: mrs, behavior: ipcidr }
    BehaviorCL: &BehaviorCL
      type: http
      interval: 86400
      format: yaml
      behavior: classical

  rule-providers:
    Lan:
      <<: *BehaviorDN
      url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs

    China:
      <<: *BehaviorDN
      url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
