- name: US【机场推荐：https://a9a.xyz】6
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  cipher: auto
  alterId: 0
  tls: false
- name: HK【机场推荐：https://a9a.xyz】53
  type: vmess
  server: 103.181.164.237
  port: 52283
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 0
  tls: false
- name: HK【机场推荐：https://a9a.xyz】62
  type: ss
  server: toy4lkdzy0c.22b74943-12ad-47f4-b705-f2defb6ffea0.org
  port: 13142
  password: >-
    mtMkp+1FttkSLmDOF9blnNMLigcCRacprQS3ry0nf3o=:AAvo+BsgpvvR5lJsdQU32vrMXL7ZAbZJZfETB7bddhQ=
  cipher: 2022-blake3-aes-256-gcm
- name: KR【机场推荐：https://a9a.xyz】56
  type: ss
  server: 141.164.45.187
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: HK【机场推荐：https://a9a.xyz】54
  type: vmess
  server: 103.181.164.145
  port: 51556
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 0
  tls: false
- name: BG【机场推荐：https://a9a.xyz】55
  type: ss
  server: 194.68.225.52
  port: 65232
  password: 6J754ee6ITjyfDysi78uqJ
  cipher: chacha20-ietf-poly1305
- name: LV【机场推荐：https://a9a.xyz】57
  type: ss
  server: 185.176.221.72
  port: 24637
  password: MholStyHL7DhrewKbpQa20
  cipher: chacha20-ietf-poly1305
- name: HK【机场推荐：https://a9a.xyz】51
  type: vmess
  server: 103.181.164.237
  port: 34114
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 0
  tls: false
- name: US【机场推荐：https://a9a.xyz】1
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  cipher: auto
  alterId: 0
  tls: false
- name: HK【机场推荐：https://a9a.xyz】2
  type: vmess
  server: 103.181.164.237
  port: 34114
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 64
  tls: false
- name: 节点日期：2026-03-18
  type: vmess
  server: 103.181.164.145
  port: 54022
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 64
  tls: false
- name: MY【机场推荐：https://a9a.xyz】1
  type: vmess
  server: v12.hdacd.com
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  cipher: auto
  alterId: 0
  tls: false
- name: ID【机场推荐：https://a9a.xyz】2
  type: vmess
  server: v30.hdacd.com
  port: 30830
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  cipher: auto
  alterId: 0
  tls: false
- name: HK【机场推荐：https://a9a.xyz】3
  type: vmess
  server: 103.181.164.145
  port: 51556
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  cipher: auto
  alterId: 0
  tls: false
- name: US【机场推荐：https://a9a.xyz】7
  type: vmess
  server: 82.198.246.250
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  cipher: auto
  alterId: 0
  tls: false
- name: CA【机场推荐：https://a9a.xyz】9
  type: vless
  server: fm3.pages.dev
  port: 443
  uuid: 873914f7-1b3d-481d-9a34-69bc85f64aac
  network: ws
  tls: true
  skip-cert-verify: false
  servername: fm3.pages.dev
  client-fingerprint: randomized
  ws-opts:
    headers:
      Host: fm3.pages.dev
    path: /?ed=2560
- name: HK【机场推荐：https://a9a.xyz】10
  type: vmess
  server: efan.dnsefan04881.com
  port: 7754
  uuid: 009e558d-3cf4-49d8-b5e4-82c9e14fe1a4
  cipher: auto
  alterId: 0
  tls: false
