# node-gyp-build: patches/node-gyp-build.patch
# patchedDependencies:
# ts-punycode@0.1.0: patches/ts-punycode@0.1.0.patch
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@5.7.2 || 6.3.1'
patchedDependencies:
  # prebuild-install: patches/prebuild-install.patch
  # registry-js: patches/registry-js.patch
  ts-punycode: patches/ts-punycode@0.1.2.patch
ignoredBuiltDependencies:
  - registry-js
onlyBuiltDependencies:
  - '@bratel/registry-js'
  - '@bratel/webcrack'
  - es5-ext
  - isolated-vm
  # - registry-js
  - ts-punycode
allowBuilds:
  '@bratel/registry-js': true
  '@bratel/webcrack': true
  es5-ext: true
  isolated-vm: true
  registry-js: true
  ts-punycode: true
