ignoredBuiltDependencies:
  - ts-punycode
# patchedDependencies:
# ts-punycode@0.1.0: patches/ts-punycode@0.1.0.patch
onlyBuiltDependencies:
  - isolated-vm
  - ts-punycode
shellEmulator: true

trustPolicy: no-downgrade
